
// This is an autogenerated file from Firebase Studio.
import { GoogleAuthProvider, signInWithPopup, User, AuthErrorCodes } from "firebase/auth";
import { auth } from "./firebase";

export const signInWithGoogle = async (): Promise<User | null> => {
  const provider = new GoogleAuthProvider();
  try {
    const result = await signInWithPopup(auth, provider);
    return result.user;
  } catch (error: any) {
    if (error.code === AuthErrorCodes.POPUP_CLOSED_BY_USER) {
      console.log("Sign-in popup closed by user.");
      return null;
    }
    console.error("Error signing in with Google: ", error);
    return null;
  }
};
