

// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApp, getApps } from "firebase/app";
import { getAuth } from "firebase/auth";

const firebaseConfig = {
  "projectId": "shedula",
  "appId": "1:182242585199:web:2df3db9dd3a8b4f6553b9a",
  "storageBucket": "shedula.firebasestorage.app",
  "apiKey": "AIzaSyBWufMRVGagou9rj_vXYSb_mOhqGssNvCU",
  "authDomain": "shedula.firebaseapp.com",
  "messagingSenderId": "182242585199",
  "measurementId": "G-XXXXXXXXXX"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);

export { app, auth };
